int _putchar(char c);
void _puts_recursion(char *s);
void _print_rev_recursion(char *s);
int _strlen_recursion(char *s);
int factorial(int n);
int _pow_recursion(int x, int y);
int who_let_the_roots_out(int rootytooty, int freshfruity);
int _sqrt_recursion(int n);
int number_chumber(int nummie, int tummie);
int is_prime_number(int n);
